package esempio04;

import java.time.LocalDate;
import java.util.Objects;

/**
 * The Persona class represents a person with a name, a surname, and a birth
 * date. This class provides methods to access and manipulate these attributes,
 * as well as to compare and display instances of the class.
 * 
 * This class was correctly autogenerated by Eclipse.
 * 
 * @author michelemazza
 *
 */
public class Persona {
	private String nome, cognome;
	private LocalDate nascita;

	/**
	 * Constructs a new Persona with the specified name, surname, and birth date.
	 * 
	 * @param nome    the name of the person
	 * @param cognome the surname of the person
	 * @param nascita the birth date of the person
	 */
	public Persona(String nome, String cognome, LocalDate nascita) {
		this.nome = nome;
		this.cognome = cognome;
		this.nascita = nascita;
	}

	/**
	 * Returns the name of the person.
	 * 
	 * @return the name of the person
	 */
	public String getNome() {
		return nome;
	}

	/**
	 * Returns the surname of the person.
	 * 
	 * @return the surname of the person
	 */
	public String getCognome() {
		return cognome;
	}

	/**
	 * Returns the birth date of the person.
	 * 
	 * @return the birth date of the person
	 */
	public LocalDate getNascita() {
		return nascita;
	}

	/**
	 * Returns a hash code for this Persona instance.
	 * 
	 * @return a hash code for this Persona instance
	 */
	@Override
	public int hashCode() {
		return Objects.hash(cognome, nascita, nome);
	}

	/**
	 * Indicates whether some other object is equal to this one.
	 * 
	 * @param obj the object to compare this instance with
	 * @return true if obj is an instance of Persona and has the same name, surname,
	 *         and birth date as this instance; false otherwise
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (!(obj instanceof Persona))
			return false;
		Persona other = (Persona) obj;
		return Objects.equals(cognome, other.cognome) && Objects.equals(nascita, other.nascita)
				&& Objects.equals(nome, other.nome);
	}

	/**
	 * Returns a string representation of this Persona instance.
	 * 
	 * @return a string representation of this Persona instance
	 */
	@Override
	public String toString() {
		return "Persona [nome=" + nome + ", cognome=" + cognome + ", nascita=" + nascita + "]";
	}
}
